### ISSUE TITLE
Docstrings for the data upload code

### ISSUE THREAD

**Issue by guysmoilov** [DagsHub/client#223]
It's pretty hard to understand how to use `Repo`, `DataSet` and related code in [`dagshub/upload/wrapper.py`](https://github.com/DagsHub/client/blob/master/dagshub/upload/wrapper.py) without more documentation.

**Comment by krishnaduttPanchagnula** [comment]
Working on it..will raise a pr once done. Please review and provide any suggestions necessary!

**Comment by krishnaduttPanchagnula** [comment]
Add the docstrings in this PR. Please review it and suggest changes, if any.

https://github.com/DagsHub/client/pull/229/commits/ee81eb3dff90da95ee18c7114f26e5fe0755b9b4
