### ISSUE TITLE
Add --verbose command line flag and improve logging

### ISSUE THREAD

**Issue by guysmoilov** [DagsHub/client#224]
Logging levels should be standardized, and generally more logs added to the most verbose level.
After doing that, a `--verbose` flag can greatly help in debugging issues

**Comment by kbolashev** [comment]
Alternatively, a DAGSHUB_LOG_LEVEL command that allows you to set the logging level

**Comment by kbolashev** [comment]
All the CLI commands have a `-v` flag that makes the output more and more verbose
