### ISSUE TITLE
Improve default behavior for repo.upload

### ISSUE THREAD

**Issue by deanp70** [DagsHub/client#281]
In this code snippet: https://github.com/DagsHub/client/blob/master/dagshub/upload/wrapper.py#L177

The doc string is not up to date.

Also, `remote_path` defaults to `None`, which then fails with a "mysterious" error when run without a remote path provided. We should make it a required parameter or provide better defaults.

**Comment by krishnaduttPanchagnula** [comment]
i have done the following in my PR #285 
- Added a better erroring mechanism to detect the if there are any arguments missing, when running a method
- Added remote_path as required parameter
- Updated the Docstring
