### ISSUE TITLE
Add `--versioning` flag for CLI upload command

### ISSUE THREAD

**Issue by deanp70** [DagsHub/client#294]
Sometimes the user wants to override our logic for whether to push a file to Git or DVC, they can not do this via the CLI currently, as `dagshub upload` doesn't have a versioning argument, and due to #293 uploading via API doesn't properly work either

**Comment by kbolashev** [comment]
@deanp70 Just letting you know that this should be fixed with the next release. Both this, and I also added the `--versioning` flag.
Tested it manually to see that it works and what's being uploaded makes sense. Will bump the version a bit later after I do some more cleanup
