### ISSUE TITLE
DDA Streaming: Listdir for non-storage directories returns only first 500 files

### ISSUE THREAD

**Issue by kbolashev** [DagsHub/client#307]
Need to implement proper paginated fetching there

**Comment by hjain5164** [comment]
Hi @kbolashev, would like to work on this task. Can you give a heads-up so that I can start.

**Comment by kbolashev** [comment]
Hi @hjain5164 ! Thank you very much for reaching out
Really sorry, but it looks like I accidentally filed this bug.
Right now our backend's pagination seems to be working a bit incorrectly, so for now the client receives all of the items at once, so this will only have to be fixed once the backend bug is fixed haha

**Comment by kbolashev** [comment]
Hi @hjain5164 !
Thanks for reaching out
I did some more tests and it seems like our backend for now returns all the files for non-storage dirs when you listdir, so seems like it's something that we should fix on the backend first before fixing in the client. I'll close this for now, but thanks so much for reaching out again
