### ISSUE TITLE
install_hooks throwing error on windows

### ISSUE THREAD

**Issue by gmilamjr** [DagsHub/client#308]
Im trying to use the data streaming capabilities from dagshub but when I run the install_hooks function its throws the attribute error shown in the attached file. Running on Windows 11, Dagshub version 0.2.17_1

[error.txt](https://github.com/DagsHub/client/files/11681827/error.txt)

**Comment by kbolashev** [comment]
Hi!
Thank you very much for the report!

I reproduced this issue and will try to resolve it as quick as I can.

**Comment by kbolashev** [comment]
Hi again @gmilamjr !
We have released a new version that should solve the issues with streaming on Windows.
Made sure to pick up a windows laptop and make sure stuff seems to be running ok :) 

Can you upgrade to `0.2.18` and tell me how it goes? Hope we can get it working, and if it doesn't I'll be glad to debug further

**Comment by gmilamjr** [comment]
All is working great @kbolashev . Thanks for the quick turnaround!
