### ISSUE TITLE
Add a download() function into the RepoAPI object

### ISSUE THREAD

**Issue by kbolashev** [DagsHub/client#363]
RepoAPI should have a `download()` function that utilizes the `common.download.download_files()` function to download the whole repo or a directory in a repo in a parallelized fashion.

```python
repo = RepoAPI("user/repo")
repo.download(outdir="/home/user/my-repo")
# OR
repo.download("data/images", "/home/user/images")
```

Probably should be recursive by default with the ability to turn it off

**Comment by itssiddhantjain** [comment]
Hello @kbolashev , please assign this issue to me as I have already worked on this kind of problem in past and has a great experience.

**Comment by kbolashev** [comment]
@itssiddhantjain Feel free to make a PR for whatever issue you want to tackle 👍

**Comment by kbolashev** [comment]
Implemented in https://github.com/DagsHub/client/pull/389
