### ISSUE TITLE
Data Engine: Allow downloading all binary fields when `qr.get_blob_fields` is called with no args

### ISSUE THREAD

**Issue by kbolashev** [DagsHub/client#366]
Right now you need to specify the columns you want to get. Would be nice to be able to download all of them at once

```python
qr = ds.all()
qr.get_blob_field() # Should download all
```

**Comment by rabroldan** [comment]
Hi there is it okay if I take this issue? also I wanted to make sure I understand it correctly are we enhancing the function def get_blob_fields to download all files when called with no args?

if so. do we want to have the option when an argument is placed we keep the downloading specification intact and if no arguments is placed we download it all automatically? or just enhance it fully where we never need an arggument and it gets downlaoded automatically?

thank you

**Comment by kbolashev** [comment]
Hi @rabroldan ! Thanks for replying to this!

You're absolutely welcome to take on this! :)
Yes, the idea is to keep the current behavior of `get_blob_fields` with being able to specify fields to download, while also allowing to download all the blob fields, if none were specified.

The argument for the `get_blob_fields` is an expanded tuple: https://github.com/DagsHub/client/blob/master/dagshub/data_engine/model/query_result.py#L210 so it should be possible to check its length to see if it's empty or not

**Comment by rabroldan** [comment]
Allright ill let you know if I need anything, ill start working on this now.

**Comment by kbolashev** [comment]
Closed with https://github.com/DagsHub/client/pull/371
Thank you for the contribution!!
