### ISSUE TITLE
Experiments Card Overflow UI issue

### ISSUE THREAD

**Issue by MartinKalema** [DagsHub/client#456]
The scroll feature doesn't seem to work. I'm trying to view the setup instructions in the "experiments" section. The card seems to have extra instructions at the bottom but i can't read them.

![dagshub-experiment](https://github.com/DagsHub/client/assets/130189437/068a57a4-4655-4c78-84ea-ab475ef0d03f)

**Comment by kbolashev** [comment]
Hi Martin!
Thanks for raising this issue, and I apologize for the subpar experience, we'll work on fixing this

Luckily it's not a lot that you're missing, the snippet after this ends with 
```python
mlflow.end_run()
```

And then it has a link to the docs: https://dagshub.com/docs/integration_guide/mlflow_tracking/

LMK if there's anything else I can help you with

**Comment by MartinKalema** [comment]
Thanks @kbolashev
