### ISSUE TITLE
Log-Model failed due to server issue

### ISSUE THREAD

**Issue by MartinKalema** [DagsHub/client#457]
**Query**
An error occurs while attempting to make an HTTPS request to https://dagshub.com/kalema3502/mlflow_test.mlflow/api/2.0/mlflow/runs/log-model, and  the server responds with many 500 error responses. 

**Screenshots**
![server-error-1](https://github.com/DagsHub/client/assets/130189437/96fa96d0-b70b-4ff4-ac65-67ca2308b275)

![server-error-2](https://github.com/DagsHub/client/assets/130189437/30051de3-86ec-40f1-859f-a8be4611de37)
![server-error-3](https://github.com/DagsHub/client/assets/130189437/c23fe0c1-b5d3-48c2-8401-da1b42185d11)

**Comment by kbolashev** [comment]
Hi!
Can you let me know which  version of MLflow you have and, if possible, give an example code of what you were doing?

**Comment by kbolashev** [comment]
Thank you, @MartinKalema !
I'll look into reproducing it on my end and report findings for you.

In the meanwhile, I know that MLflow had changes with how they're logging artifacts in recent releases, so you can try rolling back the version to `2.7.1`, which is the one our server runs right now. Maybe it will fix the problem.

We're planning on updating the MLflow version to the latest upstream soon

**Comment by MartinKalema** [comment]
@kbolashev Rolling back to version 2.7.1 solved the issue. Thanks
